{"name": "test_01", "status": "failed", "statusDetails": {"message": "Failed: Fixture \"get_env\" called directly. Fixtures are not meant to be called directly,\nbut are created automatically when test functions request them as parameters.\nSee https://docs.pytest.org/en/stable/fixture.html for more information about fixtures, and\nhttps://docs.pytest.org/en/stable/deprecations.html#calling-fixtures-directly about how to update your code.", "trace": "Fixture \"get_env\" called directly. Fixtures are not meant to be called directly,\nbut are created automatically when test functions request them as parameters.\nSee https://docs.pytest.org/en/stable/fixture.html for more information about fixtures, and\nhttps://docs.pytest.org/en/stable/deprecations.html#calling-fixtures-directly about how to update your code."}, "start": 1658394516684, "stop": 1658394516684, "uuid": "b93224d8-6cd6-4425-a9a7-02f336533067", "historyId": "1bc96a174c145df868a250f0fe299b23", "testCaseId": "6830f52eca23030a0e02d4fee5615b21", "fullName": "conftest#test_01", "labels": [{"name": "suite", "value": "conftest"}, {"name": "host", "value": "DESKTOP-B9EI7PH"}, {"name": "thread", "value": "81484-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "conftest"}]}